# Travis CI configuration

# xenial (has build-essential) + Java
dist: xenial
# we are requiring VM instead of Docker builds due to sporadic nailgun test suite failures
sudo: required
language: java

# we test for JDK 8,10,11
# (usually, but PPL is only building on Java 8 for now)
jdk:
  - openjdk8
#  - openjdk10
#  - openjdk11

install:
# Install PPL
  - wget http://www.bugseng.com/products/ppl/download/ftp/releases/1.2/ppl-1.2.tar.gz
  - tar xfz ppl-1.2.tar.gz
  - export JAVA_HOME=`which javac | sed 's/\/bin\/javac//'`
  - echo $JAVA_HOME
  - pushd ppl-1.2 && ./configure --enable-interfaces=java --with-java=$JAVA_HOME && make && sudo make install && popd
# Install Yices
#  - sudo apt-get update
#  - sudo apt -y install gperf
#  - wget https://yices.csl.sri.com/releases/2.6.0/yices-2.6.0-src.tar.gz
#  - tar xvfz yices-2.6.0-src.tar.gz
#  - pushd yices-2.6.0 && ./configure && make && sudo make install && popd

# compile and run the test suite
# we manually set PRISM_JAVA to the java on the PATH as the python invocation of prism-auto fiddles with the PATH variable...  
script: >
  cd prism &&
# cp /usr/local/lib/libyices.so.2.6 lib &&
  make PPL_DIR=/usr/local/lib &&
  echo 'Compilation successful, running test suite....' && echo &&
  export PRISM_JAVA=`which java` &&
  make tests &&
  echo && echo 'Yay'


# notifications
notifications:
  email:
    recipients:
      - d.a.parker@cs.bham.ac.uk
      - klein@tcs.inf.tu-dresden.de
    on_success: change
    on_failure: always
